Model1:
  model_type: "unigram"
  training_data_path: "DATASET/train/train_labeled.txt"
  validation_data_path: "DATASET/validation/validation_labeled.txt"
Model2:
  model_type: "bigram"
  training_data_path: "DATASET/train/train_labeled.txt"
  validation_data_path: "DATASET/validation/validation_labeled.txt"
Model3:
  model_type: "NB"
  training_data_path: "DATASET/train/train_labeled.txt"
  validation_data_path: "DATASET/validation/validation_labeled.txt"
  